### ISSUE TITLE
Cannot find name 'Expression' in binding-function-scope.d.ts

### ISSUE THREAD

**Issue by NickDarvey** [niieani/aurelia-binding-functions#1]
I added aurelia-rxjs and aurelia-binding-functions to my project but I'm having trouble compiling the BindingFunctionScope class.
The import statement at the top seems to understand the Expression interface, but BindingFunctionScope can't extend it. (This happens in the tooling and in the gulp build task.)

aurelia-binding-functions version 0.2.2

![image](https://cloud.githubusercontent.com/assets/6076697/14701838/a573c6a0-07ea-11e6-8f97-02f73b8dc415.png)

**Comment by niieani** [comment]
This is an issue with Aurelia's generated d.ts files. Expression is defined as an Interface, while it should be a Class. I changed it manually for it to compile, however you can file a bug report or a pull request to aurelia-binding about it.
